chore(gha): test more logs

diff --git a/.github/workflows/hello-default.yml b/.github/workflows/hello-default.yml
--- a/.github/workflows/hello-default.yml
+++ b/.github/workflows/hello-default.yml
@@ -29,29 +29,29 @@ jobs:
         run: |
           echo "DOCKER_HOST...$DOCKER_HOST"
           echo "DOCKER_CONTEXT...$DOCKER_CONTEXT"
-          docker info || echo "docker info failed!!!"
-          docker version || echo "docker version failed!!!"
-          docker ps || echo "docker ps failed!!!"
-          docker images || echo "docker images failed!!!"
-          docker context ls || echo "docker context ls failed!!!"
+          echo "docker info..." && docker info || echo "docker info failed!!!"
+          echo "docker version..." && docker version || echo "docker version failed!!!"
+          echo "docker ps..." && docker ps || echo "docker ps failed!!!"
+          echo "docker images..." && docker images || echo "docker images failed!!!"
+          echo "docker context ls..." && docker context ls || echo "docker context ls failed!!!"
           docker build -t $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest --push ./helloworld || echo "docker build failed!!!"
           # docker tag helloworld:latest $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest
           # docker push $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest
           echo "DOCKER_HOST...$DOCKER_HOST"
           echo "DOCKER_CONTEXT...$DOCKER_CONTEXT"
-          docker info || echo "docker info failed!!!"
-          docker version || echo "docker version failed!!!"
-          docker ps || echo "docker ps failed!!!"
-          docker images || echo "docker images failed!!!"
-          docker context ls || echo "docker context ls failed!!!"
+          echo "docker info..." && docker info || echo "docker info failed!!!"
+          echo "docker version..." && docker version || echo "docker version failed!!!"
+          echo "docker ps..." && docker ps || echo "docker ps failed!!!"
+          echo "docker images..." && docker images || echo "docker images failed!!!"
+          echo "docker context ls..." && docker context ls || echo "docker context ls failed!!!"
       - name: docker_run
         run: |
           echo "DOCKER_HOST...$DOCKER_HOST"
           echo "DOCKER_CONTEXT...$DOCKER_CONTEXT"
-          echo "docker info" && docker info || echo "docker info failed!!!"
-          echo "docker version" && docker version || echo "docker version failed!!!"
-          echo "docker ps" && docker ps || echo "docker ps failed!!!"
-          echo "docker images" && docker images || echo "docker images failed!!!"
-          echo "docker context ls" && docker context ls || echo "docker context ls failed!!!"
-          docker pull $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest
-          docker run $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest
+          echo "docker info..." && docker info || echo "docker info failed!!!"
+          echo "docker version..." && docker version || echo "docker version failed!!!"
+          echo "docker ps..." && docker ps || echo "docker ps failed!!!"
+          echo "docker images..." && docker images || echo "docker images failed!!!"
+          echo "docker context ls..." && docker context ls || echo "docker context ls failed!!!"
+          docker pull $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker pull failed!!!"
+          docker run $ECR_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/helloworld:latest || echo "docker run failed!!!"
